version: '3.8'

services:
  backend:
    build:
      context: ./LoanApi
      dockerfile: Dockerfile
    container_name: loan-api
    ports:
      - "8080:5000"  # Changed from 5000:5000 to 8080:5000
    networks:
      - loan-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000

  frontend:
    build:
      context: ./loan-website
      dockerfile: Dockerfile
    container_name: loan-website
    ports:
      - "8081:4200"  # Using port 8081 for frontend
    depends_on:
      - backend
    networks:
      - loan-network

networks:
  loan-network:
    driver: bridge